# backend/Dockerfile
FROM node:18

WORKDIR /app
COPY backend/package*.json ./
RUN npm install
COPY backend/. .

# Ensure .env is copied
COPY backend/.env.dev .env.dev

# Generate Prisma client before container runs
RUN npx prisma generate

CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed && node src/index.js"]

